
Testing on Trial 4 for Kernel scale
Traceback (most recent call last):
  File "/home/abdelmajid/workdir/cost-aware-bo/main.py", line 64, in <module>
    bo_trial(trial_number=trial, acqf=args.acqf, wandb=wandb, params=params)
  File "/home/abdelmajid/workdir/cost-aware-bo/single_trial.py", line 61, in bo_trial
    new_x, n_memoised, E_c, E_inv_c, y_pred = bo_iteration(X, Y, C, bounds=bounds, acqf_str=acqf, decay=eta, iter=iteration, params=params)
  File "/home/abdelmajid/workdir/cost-aware-bo/single_iteration.py", line 50, in bo_iteration
    mll, gp_model = get_gp_models(train_x, train_y, params=params)
  File "/home/abdelmajid/workdir/cost-aware-bo/single_iteration.py", line 12, in get_gp_models
    mll, gp_model = initialize_GP_model(X, y, params=params)
  File "/home/abdelmajid/workdir/cost-aware-bo/functions.py", line 205, in initialize_GP_model
    kernel = KERNELS[kernel]
KeyError: 'scale'