Traceback (most recent call last):
  File "/home/abdelmajid/workdir/cost-aware-bo/main.py", line 62, in <module>
    bo_trial(trial_number=trial, acqf=args.acqf, wandb=wandb, params=params)
  File "/home/abdelmajid/workdir/cost-aware-bo/single_trial.py", line 37, in bo_trial
    input_bounds = get_gen_bounds(h_ind, bound_list, funcs=chosen_functions)
  File "/home/abdelmajid/workdir/cost-aware-bo/functions.py", line 126, in get_gen_bounds
    f_bounds = func_bounds[f]
KeyError: 'branin2,hartmann3,beale2'